USE [master]
GO
/****** Object:  Database [MeditateBook]    Script Date: 01/07/2017 17:05:49 ******/
CREATE DATABASE [MeditateBook]
 CONTAINMENT = NONE
ALTER DATABASE [MeditateBook] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeditateBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MeditateBook] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MeditateBook] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MeditateBook] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MeditateBook] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MeditateBook] SET ARITHABORT OFF 
GO
ALTER DATABASE [MeditateBook] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MeditateBook] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MeditateBook] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MeditateBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MeditateBook] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MeditateBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MeditateBook] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MeditateBook] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MeditateBook] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MeditateBook] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MeditateBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MeditateBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MeditateBook] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MeditateBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MeditateBook] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MeditateBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MeditateBook] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MeditateBook] SET RECOVERY FULL 
GO
ALTER DATABASE [MeditateBook] SET  MULTI_USER 
GO
ALTER DATABASE [MeditateBook] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MeditateBook] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MeditateBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MeditateBook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MeditateBook] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MeditateBook', N'ON'
GO
ALTER DATABASE [MeditateBook] SET QUERY_STORE = OFF
GO
USE [MeditateBook]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [MeditateBook]
GO
/****** Object:  Table [dbo].[T_Article]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Article](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[title] [varchar](255) NOT NULL,
	[content] [text] NOT NULL,
	[id_creator] [bigint] NOT NULL,
	[created_date] [date] NOT NULL,
	[validated] [bit] NOT NULL,
 CONSTRAINT [PK_T_Article] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Article_Attach]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Article_Attach](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[id_article] [bigint] NOT NULL,
	[file_path] [text] NOT NULL,
 CONSTRAINT [PK_T_Article_Attach] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Article_Image]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Article_Image](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[id_article] [bigint] NOT NULL,
	[image_path] [text] NOT NULL,
 CONSTRAINT [PK_T_Article_Image] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Comment]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Comment](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[content] [text] NOT NULL,
	[id_user] [bigint] NOT NULL,
	[id_article] [bigint] NOT NULL,
	[date] [date] NOT NULL,
 CONSTRAINT [PK_T_Comment] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Language]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Language](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[shortname] [varchar](50) NOT NULL,
 CONSTRAINT [PK_T_Language] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Message]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Message](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[content] [text] NOT NULL,
	[id_sender] [bigint] NOT NULL,
	[id_receiver] [bigint] NOT NULL,
	[date] [date] NOT NULL,
 CONSTRAINT [PK_T_Message] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_Translation]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Translation](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[content] [text] NOT NULL,
	[id_language] [bigint] NOT NULL,
	[id_article] [bigint] NOT NULL,
	[id_translator] [bigint] NOT NULL,
	[validated] [bit] NOT NULL,
 CONSTRAINT [PK_T_Translation] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_User]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_User](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[password] [text] NOT NULL,
	[firstname] [varchar](255) NULL,
	[lastname] [varchar](255) NULL,
	[role] [int] NULL,
 CONSTRAINT [PK_T_User] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[T_User_Like]    Script Date: 01/07/2017 17:05:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_User_Like](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[id_user] [bigint] NOT NULL,
	[id_article] [bigint] NOT NULL,
 CONSTRAINT [PK_T_User_Like] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[T_Article]  WITH CHECK ADD  CONSTRAINT [FK_T_Article_T_User] FOREIGN KEY([id_creator])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_Article] CHECK CONSTRAINT [FK_T_Article_T_User]
GO
ALTER TABLE [dbo].[T_Article_Attach]  WITH CHECK ADD  CONSTRAINT [FK_T_Article_Attach_T_Article] FOREIGN KEY([id_article])
REFERENCES [dbo].[T_Article] ([id])
GO
ALTER TABLE [dbo].[T_Article_Attach] CHECK CONSTRAINT [FK_T_Article_Attach_T_Article]
GO
ALTER TABLE [dbo].[T_Article_Image]  WITH CHECK ADD  CONSTRAINT [FK_T_Article_Image_T_Article] FOREIGN KEY([id_article])
REFERENCES [dbo].[T_Article] ([id])
GO
ALTER TABLE [dbo].[T_Article_Image] CHECK CONSTRAINT [FK_T_Article_Image_T_Article]
GO
ALTER TABLE [dbo].[T_Comment]  WITH CHECK ADD  CONSTRAINT [FK_T_Comment_T_Article] FOREIGN KEY([id_article])
REFERENCES [dbo].[T_Article] ([id])
GO
ALTER TABLE [dbo].[T_Comment] CHECK CONSTRAINT [FK_T_Comment_T_Article]
GO
ALTER TABLE [dbo].[T_Comment]  WITH CHECK ADD  CONSTRAINT [FK_T_Comment_T_User] FOREIGN KEY([id_user])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_Comment] CHECK CONSTRAINT [FK_T_Comment_T_User]
GO
ALTER TABLE [dbo].[T_Message]  WITH CHECK ADD  CONSTRAINT [FK_T_Message_T_User] FOREIGN KEY([id_sender])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_Message] CHECK CONSTRAINT [FK_T_Message_T_User]
GO
ALTER TABLE [dbo].[T_Message]  WITH CHECK ADD  CONSTRAINT [FK_T_Message_T_User1] FOREIGN KEY([id_receiver])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_Message] CHECK CONSTRAINT [FK_T_Message_T_User1]
GO
ALTER TABLE [dbo].[T_Translation]  WITH CHECK ADD  CONSTRAINT [FK_T_Translation_T_Article] FOREIGN KEY([id_article])
REFERENCES [dbo].[T_Article] ([id])
GO
ALTER TABLE [dbo].[T_Translation] CHECK CONSTRAINT [FK_T_Translation_T_Article]
GO
ALTER TABLE [dbo].[T_Translation]  WITH CHECK ADD  CONSTRAINT [FK_T_Translation_T_Language] FOREIGN KEY([id_language])
REFERENCES [dbo].[T_Language] ([id])
GO
ALTER TABLE [dbo].[T_Translation] CHECK CONSTRAINT [FK_T_Translation_T_Language]
GO
ALTER TABLE [dbo].[T_Translation]  WITH CHECK ADD  CONSTRAINT [FK_T_Translation_T_User] FOREIGN KEY([id_translator])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_Translation] CHECK CONSTRAINT [FK_T_Translation_T_User]
GO
ALTER TABLE [dbo].[T_User_Like]  WITH CHECK ADD  CONSTRAINT [FK_T_User_Like_T_Article] FOREIGN KEY([id_article])
REFERENCES [dbo].[T_Article] ([id])
GO
ALTER TABLE [dbo].[T_User_Like] CHECK CONSTRAINT [FK_T_User_Like_T_Article]
GO
ALTER TABLE [dbo].[T_User_Like]  WITH CHECK ADD  CONSTRAINT [FK_T_User_Like_T_User] FOREIGN KEY([id_user])
REFERENCES [dbo].[T_User] ([id])
GO
ALTER TABLE [dbo].[T_User_Like] CHECK CONSTRAINT [FK_T_User_Like_T_User]
GO
USE [master]
GO
ALTER DATABASE [MeditateBook] SET  READ_WRITE 
GO
