//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditateBook.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeditateBookEntities : DbContext
    {
        public MeditateBookEntities()
            : base("name=MeditateBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Article> T_Article { get; set; }
        public virtual DbSet<T_Article_Attach> T_Article_Attach { get; set; }
        public virtual DbSet<T_Article_Image> T_Article_Image { get; set; }
        public virtual DbSet<T_Comment> T_Comment { get; set; }
        public virtual DbSet<T_Language> T_Language { get; set; }
        public virtual DbSet<T_Message> T_Message { get; set; }
        public virtual DbSet<T_Translation> T_Translation { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_User_Like> T_User_Like { get; set; }
    }
}
